fname = input("Input your First Name : ")
lname = input("Input your Last Name : ")
print ("Hello  " + lname + " " + fname)
print("what is your favorite number?")
fav_num = input("input favorite number : ")
print("oh, Mr. " + lname + " your favorite number is " + fav_num)